# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.11
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_quaternion', [dirname(__file__)])
        except ImportError:
            import _quaternion
            return _quaternion
        if fp is not None:
            try:
                _mod = imp.load_module('_quaternion', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _quaternion = swig_import_helper()
    del swig_import_helper
else:
    import _quaternion
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class EulerAnglesStruct(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, EulerAnglesStruct, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, EulerAnglesStruct, name)
    __repr__ = _swig_repr
    __swig_setmethods__["roll"] = _quaternion.EulerAnglesStruct_roll_set
    __swig_getmethods__["roll"] = _quaternion.EulerAnglesStruct_roll_get
    if _newclass:roll = _swig_property(_quaternion.EulerAnglesStruct_roll_get, _quaternion.EulerAnglesStruct_roll_set)
    __swig_setmethods__["pitch"] = _quaternion.EulerAnglesStruct_pitch_set
    __swig_getmethods__["pitch"] = _quaternion.EulerAnglesStruct_pitch_get
    if _newclass:pitch = _swig_property(_quaternion.EulerAnglesStruct_pitch_get, _quaternion.EulerAnglesStruct_pitch_set)
    __swig_setmethods__["yaw"] = _quaternion.EulerAnglesStruct_yaw_set
    __swig_getmethods__["yaw"] = _quaternion.EulerAnglesStruct_yaw_get
    if _newclass:yaw = _swig_property(_quaternion.EulerAnglesStruct_yaw_get, _quaternion.EulerAnglesStruct_yaw_set)
    def __init__(self): 
        this = _quaternion.new_EulerAnglesStruct()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _quaternion.delete_EulerAnglesStruct
    __del__ = lambda self : None;
EulerAnglesStruct_swigregister = _quaternion.EulerAnglesStruct_swigregister
EulerAnglesStruct_swigregister(EulerAnglesStruct)

class Quaternion(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Quaternion, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Quaternion, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _quaternion.new_Quaternion(*args)
        try: self.this.append(this)
        except: self.this = this
    def getConjugate(self): return _quaternion.Quaternion_getConjugate(self)
    def getEulerAngles(self): return _quaternion.Quaternion_getEulerAngles(self)
    __swig_destroy__ = _quaternion.delete_Quaternion
    __del__ = lambda self : None;
Quaternion_swigregister = _quaternion.Quaternion_swigregister
Quaternion_swigregister(Quaternion)

# This file is compatible with both classic and new-style classes.


